In [1]:
from shapely import geometry
import geopandas as gpd
import pandas as pd
import os
import numpy as np

In [2]:
coord_list = pd.read_csv("Coordinates-Binning3.csv")
def Coord_lister(Loc_Column):
    crs = {'init': 'epsg:4326'}
    x = Loc_Column.to_list()
    pointList = [item for item in x if str(item) != 'nan']
    pointL = []
    for x in pointList:
        y = eval(x)
        pointL.append(y)
    poly = geometry.Polygon(pointL)
    spoly = gpd.GeoSeries([poly],crs=crs)
    return spoly
He_Shop = Coord_lister(coord_list["HE shop"])
Crusher = Coord_lister(coord_list["Crusher"])
Annex_A = Coord_lister(coord_list["Annex A"])
Carmen_pit = Coord_lister(coord_list["Carmen Pit"])

Location_list = [He_Shop,Crusher, Annex_A, Carmen_pit]
Location_list_names = ["He_Shop","Crusher", "Annex_A", "Carmen Pit"]

C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pyproj\crs\crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pyproj\crs\crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pyproj\crs\crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pyproj\crs\crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)

In [3]:
file = '33854 Feb.csv'
crs = {'init': 'epsg:4326'}

#Create a geoseries holding the single polygon. Coordinates in counter-clockwise order
#pointList = [(10.325852, 123.726840), (10.331532, 123.718828), (10.337319, 123.724241), (10.341579, 123.727525), (10.340266, 123.732830), (10.333982, 123.733516)]

#Create geodataframe of points
dfcsv = pd.read_csv(file)
dfcsv

,Time,Latitude,Longitude,VehicleSpeed[km/h],Waiting Time
0,2023-02-04 23:00:46,10.336249,123.721581,0.0,1.0
1,2023-02-04 23:00:47,10.336246,123.721581,0.0,1.0
2,2023-02-04 23:00:48,10.336243,123.721581,0.0,1.0
3,2023-02-04 23:00:49,10.336239,123.721573,0.0,1.0
4,2023-02-04 23:00:50,10.336236,123.721573,0.0,1.0
...,...,...,...,...,...
568837,2023-02-12 00:21:32,10.323801,123.718292,3.6,0.0
568838,2023-02-12 00:21:33,10.323808,123.718285,3.0,0.0
568839,2023-02-12 00:21:34,10.323814,123.718285,2.6,0.0
568840,2023-02-12 00:21:35,10.323816,123.718277,2.9,0.0
568841,2023-02-12 00:21:36,10.323821,123.718277,4.0,0.0

In [4]:
geometry = [geometry.Point(xy) for xy in zip(dfcsv.Latitude, dfcsv.Longitude)]
dfpoints = gpd.GeoDataFrame(dfcsv, crs=crs, geometry=geometry)
dfpoints

C:\Users\User\AppData\Roaming\Python\Python310\site-packages\pyproj\crs\crs.py:141: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)

,Time,Latitude,Longitude,VehicleSpeed[km/h],Waiting Time,geometry
0,2023-02-04 23:00:46,10.336249,123.721581,0.0,1.0,POINT (10.33625 123.72158)
1,2023-02-04 23:00:47,10.336246,123.721581,0.0,1.0,POINT (10.33625 123.72158)
2,2023-02-04 23:00:48,10.336243,123.721581,0.0,1.0,POINT (10.33624 123.72158)
3,2023-02-04 23:00:49,10.336239,123.721573,0.0,1.0,POINT (10.33624 123.72157)
4,2023-02-04 23:00:50,10.336236,123.721573,0.0,1.0,POINT (10.33624 123.72157)
...,...,...,...,...,...,...
568837,2023-02-12 00:21:32,10.323801,123.718292,3.6,0.0,POINT (10.32380 123.71829)
568838,2023-02-12 00:21:33,10.323808,123.718285,3.0,0.0,POINT (10.32381 123.71828)
568839,2023-02-12 00:21:34,10.323814,123.718285,2.6,0.0,POINT (10.32381 123.71828)
568840,2023-02-12 00:21:35,10.323816,123.718277,2.9,0.0,POINT (10.32382 123.71828)
568841,2023-02-12 00:21:36,10.323821,123.718277,4.0,0.0,POINT (10.32382 123.71828)

In [5]:
#Create a subset dataframe of points within the polygon
for x,y in zip(Location_list, Location_list_names):
    dfpoints.loc[dfpoints.within(x.geometry.iloc[0]), "Location"] = y
dfpoints.pivot_table(index = "Location")
dfpoints.loc[dfpoints["Location"].isna(), "Location"] = "Others"
dfpoints

C:\Users\User\AppData\Local\Temp\ipykernel_4112\2680272746.py:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  dfpoints.pivot_table(index = "Location")

,Time,Latitude,Longitude,VehicleSpeed[km/h],Waiting Time,geometry,Location
0,2023-02-04 23:00:46,10.336249,123.721581,0.0,1.0,POINT (10.33625 123.72158),Crusher
1,2023-02-04 23:00:47,10.336246,123.721581,0.0,1.0,POINT (10.33625 123.72158),Crusher
2,2023-02-04 23:00:48,10.336243,123.721581,0.0,1.0,POINT (10.33624 123.72158),Crusher
3,2023-02-04 23:00:49,10.336239,123.721573,0.0,1.0,POINT (10.33624 123.72157),Crusher
4,2023-02-04 23:00:50,10.336236,123.721573,0.0,1.0,POINT (10.33624 123.72157),Crusher
...,...,...,...,...,...,...,...
568837,2023-02-12 00:21:32,10.323801,123.718292,3.6,0.0,POINT (10.32380 123.71829),Others
568838,2023-02-12 00:21:33,10.323808,123.718285,3.0,0.0,POINT (10.32381 123.71828),Others
568839,2023-02-12 00:21:34,10.323814,123.718285,2.6,0.0,POINT (10.32381 123.71828),Others
568840,2023-02-12 00:21:35,10.323816,123.718277,2.9,0.0,POINT (10.32382 123.71828),Others
568841,2023-02-12 00:21:36,10.323821,123.718277,4.0,0.0,POINT (10.32382 123.71828),Others

In [6]:
print("Data Successfully Combined")
export_state = False
while not export_state:
    export_path = input("Please input export path directory \n")
    if os.path.exists(export_path) == False:
        print("Please input a correct file path")
    else:
        export_state = True
csv_fname = input("Please input filename")
export_fpath = export_path + "\\" + csv_fname + ".csv"
print(export_fpath)
dfpoints.to_csv(path_or_buf = export_fpath, index = False)

Data Successfully Combined

Please input export path directory
 D:\KOmatsu\9. 1st Assignment - CCC\1.2 Technical Reports\2023_04_20 Payload Report and HD785 Peformance\Payload\Performance\Feb 33854 Processed
Please input filename 33854 Processed with Loc

D:\KOmatsu\9. 1st Assignment - CCC\1.2 Technical Reports\2023_04_20 Payload Report and HD785 Peformance\Payload\Performance\Feb 33854 Processed\33854 Processed with Loc.csv

In [7]:
dfpoints.drop_duplicates(keep = False)

,Time,Latitude,Longitude,VehicleSpeed[km/h],Waiting Time,geometry,Location
0,2023-02-04 23:00:46,10.336249,123.721581,0.0,1.0,POINT (10.33625 123.72158),Crusher
1,2023-02-04 23:00:47,10.336246,123.721581,0.0,1.0,POINT (10.33625 123.72158),Crusher
2,2023-02-04 23:00:48,10.336243,123.721581,0.0,1.0,POINT (10.33624 123.72158),Crusher
3,2023-02-04 23:00:49,10.336239,123.721573,0.0,1.0,POINT (10.33624 123.72157),Crusher
4,2023-02-04 23:00:50,10.336236,123.721573,0.0,1.0,POINT (10.33624 123.72157),Crusher
...,...,...,...,...,...,...,...
568837,2023-02-12 00:21:32,10.323801,123.718292,3.6,0.0,POINT (10.32380 123.71829),Others
568838,2023-02-12 00:21:33,10.323808,123.718285,3.0,0.0,POINT (10.32381 123.71828),Others
568839,2023-02-12 00:21:34,10.323814,123.718285,2.6,0.0,POINT (10.32381 123.71828),Others
568840,2023-02-12 00:21:35,10.323816,123.718277,2.9,0.0,POINT (10.32382 123.71828),Others
568841,2023-02-12 00:21:36,10.323821,123.718277,4.0,0.0,POINT (10.32382 123.71828),Others